const frutas = new Array("Uva", "Goiaba","Melancia","Manga", "Abacaxi")
console.log(frutas.join(" | "))
console.log (frutas.pop())
console.log (frutas.join(" | "))
frutas.push("kiwi")
console.log (frutas.join(" | "))
frutas.push("Melão")
console.log (frutas.join(" | "))
frutas.shift()
console.log (frutas.join(" | "))
frutas.unshift("Limão")
console.log (frutas.join(" | "))
frutas.splice(4,0, "Abacaxi")
console.log (frutas.join(" | "))
 let outrasFrutas=frutas.slice(2,4)
console.log (frutas.join(" | "))
console.log (outrasFrutas.join(" | "))
frutas.sort()
console.log (frutas.join(" | "))
frutas.reverse()
console.log (frutas.join(" | "))
